export const FETCH_AUTHORS_REQUEST = "FETCH_AUTHORS_PENDING"
export const FETCH_AUTHORS_SUCCESS = "FETCH_AUTHORS_SUCCESS"
export const FETCH_AUTHORS_FAILED = "FETCH_AUTHORS_FAILED" 

export const SEARCH_UPDATE_TERM = "SEARCH_UPDATE_TERM"